# Generated by Django 4.1.7 on 2023-05-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_a_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='a_url',
            new_name='game_html',
        ),
    ]
