# Generated by Django 4.1.7 on 2023-05-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='game_html',
        ),
    ]
